spring:
  application:
    name: CrudWithMongoDB
  data:
    mongodb:
      uri: mongodb://localhost:27017/EvenementDB
  mail:
    host: smtp.gmail.com
    port: 587
    username: imabionoor@gmail.com
    password: dfkd cljn idcp vudl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8081